### ISSUE TITLE
rainmaker /led_light not build (AEGHB-746)

### ISSUE THREAD

**Issue by ruslanslobozhenuk** [espressif/esp-mesh-lite#107]
Example rainmaker/led_light not build. Can help me? (ESP-IDF 5.2.2)

CMake Error at C:/SysGCC/esp32/5.2/esp-idf/v5.2.2/tools/cmake/build.cmake:544 (message):
  WARNING: 'git --work-tree=.  -C
  C:\Users\Ruslan\AppData\Local\Temp\tmpmatf4zzo --git-dir
  C:\Users\Ruslan\AppData\Local\Espressif\ComponentManager\Cache\b_git_5cbb1e8d
  submodule update --init --recursive' failed with exit code 128

  fatal: No url found for submodule path 'components/json_generator/upstream'
  in .gitmodules

**Comment by tswen** [comment]
You can delete this C:\Users\Ruslan\AppData\Local\Espressif\ComponentManager\ and recompile and try again

**Comment by ruslanslobozhenuk** [comment]
Thank you!!! Worked!
