### ISSUE TITLE
ESP-IDF v5.3 example led_light not build (AEGHB-755)

### ISSUE THREAD

**Issue by ruslanslobozhenuk** [espressif/esp-mesh-lite#109]
ESP-IDF v5.3 example led_light not build (((

ESP RainMaker Project commit: HEAD-HASH-NOTFOUND
error: patch failed: src/core/ipv4/dhcp.c:689
error: src/core/ipv4/dhcp.c: patch does not apply
error: patch failed: components/lwip/apps/dhcpserver/dhcpserver.c:1267
error: components/lwip/apps/dhcpserver/dhcpserver.c: patch does not apply
error: patch failed: src/core/ipv4/ip4.c:332
error: src/core/ipv4/ip4.c: patch does not apply
error: patch failed: src/core/ipv4/ip4_napt.c:1075
error: src/core/ipv4/ip4_napt.c: patch does not apply
fatal: not a git repository (or any of the parent directories): .git
-- IOT_BRIDGE: 0.11.8
error: patch failed: components/wifi_provisioning/include/wifi_provisioning/manager.h:42
error: components/wifi_provisioning/include/wifi_provisioning/manager.h: patch does not apply
error: patch failed: components/wifi_provisioning/include/wifi_provisioning/wifi_config.h:72
error: components/wifi_provisioning/include/wifi_provisioning/wifi_config.h: patch does not apply
error: patch failed: components/wifi_provisioning/proto-c/wifi_config.pb-c.c:418
error: components/wifi_provisioning/proto-c/wifi_config.pb-c.c: patch does not apply
error: patch failed: components/wifi_provisioning/proto-c/wifi_config.pb-c.h:10
error: components/wifi_provisioning/proto-c/wifi_config.pb-c.h: patch does not apply
error: patch failed: components/wifi_provisioning/proto-c/wifi_constants.pb-c.h:10
error: components/wifi_provisioning/proto-c/wifi_constants.pb-c.h: patch does not apply
error: patch failed: components/wifi_provisioning/proto-c/wifi_scan.pb-c.h:10
error: components/wifi_provisioning/proto-c/wifi_scan.pb-c.h: patch does not apply
error: patch failed: components/wifi_provisioning/proto/wifi_config.proto:21
error: components/wifi_provisioning/proto/wifi_config.proto: patch does not apply
error: patch failed: components/wifi_provisioning/src/handlers.c:20
error: components/wifi_provisioning/src/handlers.c: patch does not apply
error: patch failed: components/wifi_provisioning/src/wifi_config.c:177
error: components/wifi_provisioning/src/wifi_config.c: patch does not apply

If i make project, i have this error:

../esp-idf/v5.3/components/wifi_provisioning/src/manager.c: In function 'wifi_prov_mgr_configure_meshlite':
../esp-idf/v5.3/components/wifi_provisioning/src/manager.c:1340:22: error: 'WIFI_PROV_CUST_DATA_RECV' undeclared (first use in this function); did you mean 'WIFI_PROV_CRED_RECV'?
 1340 |     execute_event_cb(WIFI_PROV_CUST_DATA_RECV, data, size);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~
      |                      WIFI_PROV_CRED_RECV

**Comment by tswen** [comment]
You need to make sure that these patches are applied to idf. If you do not use the zero-configuration function of the mesh lite component, you can also just add the following patch
```c
diff --git a/components/wifi_provisioning/include/wifi_provisioning/manager.h b/components/wifi_provisioning/include/wifi_provisioning/manager.h
index 72c6d6d50b..7d9c6e74b3 100644
--- a/components/wifi_provisioning/include/wifi_provisioning/manager.h
+++ b/components/wifi_provisioning/include/wifi_provisioning/manager.h
@@ -42,6 +42,7 @@ typedef enum {
      * to the corresponding `wifi_sta_config_t` structure
      */
     WIFI_PROV_CRED_RECV,
+    WIFI_PROV_CUST_DATA_RECV,
 
     /**
      * Emitted when device fails to connect to the AP of which the
```
