### ISSUE TITLE
layer 2 using with mqtt error (AEGHB-769)

### ISSUE THREAD

**Issue by rikkapro0128** [espressif/esp-mesh-lite#111]
Even though layer 1 has a network connection, layer 2 is very susceptible to mqtt socket errors. I still haven't determined the cause. Have you often had this problem when trying with mqtt?

**Comment by rikkapro0128** [comment]
![Screenshot 2024-08-01 140120](https://github.com/user-attachments/assets/f0d8085c-e759-47d4-bdbc-0905f48a1435)

**Comment by tswen** [comment]
How many devices are there in the current network?
In addition, what are the two configuration items CONFIG_BRIDGE_IP_NAPT_SIZE and CONFIG_BRIDGE_IP_NAPT_TIMEOUT_MS_TCP in your project?

**Comment by rikkapro0128** [comment]
my current network is 10 device 
CONFIG_BRIDGE_IP_NAPT_SIZE
![Screenshot 2024-08-09 110807](https://github.com/user-attachments/assets/53cb364e-2ab7-4f0a-8f82-8e0f17459308)
CONFIG_BRIDGE_IP_NAPT_TIMEOUT_MS_TCP
![Screenshot 2024-08-09 111021](https://github.com/user-attachments/assets/c38fa4b6-854d-467d-8257-3d8777815e9b)

**Comment by rikkapro0128** [comment]
> How many devices are there in the current network? In addition, what are the two configuration items CONFIG_BRIDGE_IP_NAPT_SIZE and CONFIG_BRIDGE_IP_NAPT_TIMEOUT_MS_TCP in your project?

Currently, I still see packets sent from the server, but every time the server sends data it reports a socket error. I don't know exactly what is going on and whether this error is due to the application layer or not.

**Comment by rikkapro0128** [comment]
Currently I am on version 1.0.0 and am currently having an error about the 2nd layer mqtt and the device cannot create a mesh network if it is 1m or more away, however if I return to version 0.10.6 everything works. still fine in terms of mesh creation ability, however the mqtt problem of the 2nd layer about the socket is still there but it only occasionally encounters that situation

**Comment by robocircuits** [comment]
I am facing a somewhat similar issue. I am using ESP_MESH_LITE with AWS IoT MQTT connection. 
The connection is very instable and I am getting delays in telemetry and commands.

**Comment by rikkapro0128** [comment]
![Screenshot (7)](https://github.com/user-attachments/assets/80cd9a6e-e9b5-4160-9aaf-28b10ee63209)
![Screenshot (6)](https://github.com/user-attachments/assets/940e0395-b450-4bda-9ca1-53cb7fbe863e)

**Comment by robocircuits** [comment]
<img width="793" alt="Screenshot 2024-08-10 at 10 34 03 PM" src="https://github.com/user-attachments/assets/36d1503f-0085-41b2-abad-1c25cce851e5">

**Comment by tswen** [comment]
这个和 

> Currently I am on version 1.0.0 and am currently having an error about the 2nd layer mqtt and the device cannot create a mesh network if it is 1m or more away, however if I return to version 0.10.6 everything works. still fine in terms of mesh creation ability, however the mqtt problem of the 2nd layer about the socket is still there but it only occasionally encounters that situation

What does `the device cannot create a mesh network` mean? Is the Wi-Fi connection failed? Can you provide a complete log file from power on?

**Comment by rikkapro0128** [comment]
> > Currently I am on version 1.0.0 and am currently having an error about the 2nd layer mqtt and the device cannot create a mesh network if it is 1m or more away, however if I return to version 0.10.6 everything works. still fine in terms of mesh creation ability, however the mqtt problem of the 2nd layer about the socket is still there but it only occasionally encounters that situation
> 
> What does `the device cannot create a mesh network` mean? Is the Wi-Fi connection failed? Can you provide a complete log file from power on?

- this means that these devices are mostly layer 1, they have difficulty connecting to each other compared to version 0.10.6, as I see it
- With 0.10.6, I'm still having an mqtt socket error at layer 2. Can you please diagnose the error for me? Layer 1 still has normal mqtt operation. I suspect TCP packet forwarding is having problems. problem

**Comment by tswen** [comment]
你有通过 esp_mesh_lite_set_networking_mode 设置 ESP_MESH_LITE_ROUTER 模式吗？
另外你说的 1.0.0 是通过 components register 拉下来的组件，还是 esp-mesh-lite 仓库 master 分支最新的组件，建议用 master 最新的。

**Comment by rikkapro0128** [comment]
> Have you set the ESP_MESH_LITE_ROUTER mode via esp_mesh_lite_set_networking_mode? In addition, the 1.0.0 you mentioned is the component pulled down through the components register, or the latest component of the master branch of the esp-mesh-lite repository. It is recommended to use the latest master.

- No, I never called that function in my code
- now I'm only using version 0.10.6
- I noticed it only really moves from level 1 to level 2, 3, 4... when your internal code calls the function esp_mesh_lite_wifi_scan_start()
- Once it has connected to the router, it does not change the level (from level 1 to 2) or a long time later it calls the function esp_mesh_lite_wifi_scan_start in your internal code and it begins to change the level (time can take quite a bit longer than 10 minutes for example, I've seen that)
- Is there any way for me to be proactive in searching for mesh networks (I set the soft-ap network interfaces of the esp to hidden wifi_cfg.ap.ssid_hidden = 1;)
- Can you advise me to fix the mqtt problem or please test with mqtt again to see if the tcp socket handle has any problems?
