### ISSUE TITLE
MQTT with MESH-LITE Error :  mqtt_client: esp_mqtt_handle_transport_read_error: transport_read(): EOF  (AEGHB-777)

### ISSUE THREAD

**Issue by robocircuits** [espressif/esp-mesh-lite#114]
I am connecting to AWS IoT Core using my esp32 in mesh network. I am getting the following errors.

<img width="793" alt="Screenshot 2024-08-12 at 11 26 02 AM" src="https://github.com/user-attachments/assets/fb786e4c-6dcf-4b38-b31b-656469cfc519">

The connection is not stable. Can anyone suggest me how can I make it more stable and better.

**Comment by yel-best** [comment]
Hi, 

What version of` mesh lite `are you using?

How many esp32s are there? Can you try to connect MQTT in the local LAN to see if there will be any problems?

**Comment by robocircuits** [comment]
This was issue due to multiple same client_id connecting to broker. i changed names and it worked fine after that.

**Comment by yel-best** [comment]
> This was issue due to multiple same client_id connecting to broker. i changed names and it worked fine after that.

Glad to see your problem has been solved 😄
