### ISSUE TITLE
请求出一个no-router的example (AEGHB-361)

### ISSUE THREAD

**Issue by FlandreUNX** [espressif/esp-mesh-lite#24]
现行项目使用esp-mdf, 我从mdf_no-router迁移过来, 发现大有不同, 请求做一个example指示如何做no-router

**Comment by tswen** [comment]
可以参考 https://github.com/tswen/esp-mesh-lite/tree/examples/add_no_router_example/examples/no_router。
等文档相关内容完善好了会 release 出去。

**Comment by FlandreUNX** [comment]
> 

谢谢!
