### ISSUE TITLE
no Internet access from devices connected to the router (AEGHB-399)

### ISSUE THREAD

**Issue by hard-cat** [espressif/esp-mesh-lite#31]
the root device is connected to a Wi-Fi router with the Internet, the second board is connected to the root device, this can be seen in the logs.
- The root device successfully completes the http request
- The connected device to the root device cannot fulfill the HTTP request
- local access via UDP between devices is available
- The firmware is the same in both boards with ESP32
- ESP-IDF v4.4.1-dirty
- esp-mesh-lite 0.7

`
I (28) boot: ESP-IDF v4.4.1-dirty 2nd stage bootloader
I (28) boot: compile time 16:24:26
I (28) boot: chip revision: 3
I (31) qio_mode: Enabling default flash chip QIO
I (37) boot.esp32: SPI Speed      : 80MHz
I (41) boot.esp32: SPI Mode       : QIO
I (46) boot.esp32: SPI Flash Size : 8MB
I (50) boot: Enabling RNG early entropy source...
I (56) boot: Partition Table:
I (59) boot: ## Label            Usage          Type ST Offset   Length
I (67) boot:  0 sec_cert         unknown          3f 06 0000d000 00003000
I (74) boot:  1 nvs              WiFi data        01 02 00010000 00006000
I (82) boot:  2 otadata          OTA data         01 00 00016000 00002000
I (89) boot:  3 phy_init         RF data          01 01 00018000 00001000
I (97) boot:  4 ota_0            OTA app          00 10 00020000 002c9000
I (104) boot:  5 ota_1            OTA app          00 11 002f0000 002c9000
I (112) boot:  6 events           NVS keys         01 04 005b9000 00100000
I (119) boot:  7 keys             NVS keys         01 04 006b9000 00100000
I (127) boot:  8 factory_nvs      WiFi data        01 02 007b9000 00006000
I (134) boot:  9 nvs_keys         NVS keys         01 04 007bf000 00001000
I (142) boot: 10 coredump         Unknown data     01 03 007c0000 00010000
I (149) boot: 11 datalogic        NVS keys         01 04 007d0000 00020000
I (157) boot: End of partition table
I (161) boot: No factory image, trying OTA 0
I (166) esp_image: segment 0: paddr=00020020 vaddr=3f400020 size=94130h (606512) map
I (342) esp_image: segment 1: paddr=000b4158 vaddr=3ffbdb60 size=05b34h ( 23348) load
I (349) esp_image: segment 2: paddr=000b9c94 vaddr=40080000 size=06384h ( 25476) load
I (358) esp_image: segment 3: paddr=000c0020 vaddr=400d0020 size=1341b8h (1262008) map
I (705) esp_image: segment 4: paddr=001f41e0 vaddr=40086384 size=192f0h (103152) load
I (739) esp_image: segment 5: paddr=0020d4d8 vaddr=50000000 size=00010h (    16) load
I (755) boot: Loaded app from partition at offset 0x20000
I (819) boot: Set actual ota_seq=1 in otadata[0]
I (819) boot: Disabling RNG early entropy source...
I (830) psram: This chip is ESP32-PICO-V3-02
I (830) spiram: Found 16MBit SPI RAM device
I (830) spiram: SPI RAM mode: flash 80m sram 80m
I (836) spiram: PSRAM initialized, cache is in low/high (2-core) mode.
I (843) cpu_start: Pro cpu up.
I (847) cpu_start: Starting app cpu, entry point is 0x400819f4
0x400819f4: call_start_cpu1 at C:/esp/esp-idf-v4.4.1/components/esp_system/port/cpu_start.c:160

I (0) cpu_start: App cpu up.
I (1104) spiram: SPI SRAM memory test OK
I (1113) cpu_start: Pro cpu start user code
I (1113) cpu_start: cpu freq: 240000000
I (1113) cpu_start: Application information:
I (1116) cpu_start: Project name:     
I (1122) cpu_start: App version:      ca29a8c-dirty
I (1127) cpu_start: Compile time:     Sep 22 2023 10:40:12
I (1133) cpu_start: ELF file SHA256:  afe71a7ff0d90cbd...
I (1139) cpu_start: ESP-IDF:          v4.4.1-dirty
I (1145) heap_init: Initializing. RAM available for dynamic allocation:
I (1152) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (1158) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (1165) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (1171) heap_init: At 3FFC8200 len 00017E00 (95 KiB): DRAM
I (1177) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1183) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1190) heap_init: At 4009F674 len 0000098C (2 KiB): IRAM
I (1196) spiram: Adding pool of 2020K of external SPI memory to heap allocator
I (1205) spi_flash: detected chip: generic
I (1209) spi_flash: flash io: qio
I (1214) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (1228) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations
I (1292) : Reset Reason : 1, 101
I (1318) gpio: GPIO[4]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:1
I (3609) I2S: APLL expected frequency is 24576000 Hz, real frequency is 24575996 Hz
I (3610) I2S: DMA Malloc info, datalen=blocksize=2400, dma_buf_count=3
E (3614) MY_BOARD_V1_0: i2s port 1 is not supported
I (3620) I2S: DMA queue destroyed
I (3624) I2S: APLL expected frequency is 24576000 Hz, real frequency is 24575996 Hz
I (3632) I2S: DMA Malloc info, datalen=blocksize=2400, dma_buf_count=3
I (3646) AUDIO_PIPELINE: link el->rb, el:0x3f80bf54, tag:i2s, rb:0x3f80c540
I (3735) BTDM_INIT: BT controller compile version [5688ed5]
I (3736) system_api: Base MAC address is not set
I (3740) system_api: read default base MAC address from EFUSE
I (3749) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (4179) bridge_common: esp-iot-bridge version: 0.7.1
I (4186) wifi:wifi driver task: 3ffed19c, prio:23, stack:6656, core=0
I (4191) wifi:wifi firmware version: 63017e0
I (4194) wifi:wifi certification version: v7.0
I (4198) wifi:config NVS flash: disabled
I (4202) wifi:config nano formating: disabled
I (4206) wifi:Init data frame dynamic rx buffer num: 16
I (4211) wifi:Init management frame dynamic rx buffer num: 16
I (4216) wifi:Init management short buffer num: 32
I (4221) wifi:Init static tx buffer num: 8
I (4225) wifi:Init tx cache buffer num: 16
I (4228) wifi:Init static rx buffer size: 1600
I (4233) wifi:Init static rx buffer num: 8
I (4236) wifi:Init dynamic rx buffer num: 16
I (4243) wifi_init: tcpip mbox: 64
I (4244) wifi_init: udp mbox: 64
I (4248) wifi_init: tcp mbox: 6
I (4252) wifi_init: tcp tx win: 65535
I (4256) wifi_init: tcp rx win: 4380
I (4261) wifi_init: tcp mss: 1460
I (4265) wifi_init: WiFi/LWIP prefer SPIRAM
I (4270) wifi_init: WiFi IRAM OP enabled
I (4274) wifi_init: LWIP IRAM OP enabled
I (4280) wifi:mode : null
I (4284) ip select: IP Address:192.168.4.1
I (4286) ip select: GW Address:192.168.4.1
I (4291) ip select: NM Address:255.255.255.0
I (4296) bridge_wifi: IP Address:192.168.4.1
Add netif ap with ca29a8c(commit id)
I (4304) bridge_common: netif list add success
I (4310) wifi:mode : softAP (e8:9f:6d:32:00:29)
I (4314) wifi:Total power save buffer number: 4
I (4317) wifi:Init max length of beacon: 752/752
I (4322) wifi:Init max length of beacon: 752/752
Add netif sta with ca29a8c(commit id)
I (4330) bridge_common: netif list add success
I (4335) wifi:mode : sta (e8:9f:6d:32:00:28) + softAP (e8:9f:6d:32:00:29)
I (4341) wifi:enable tsf
I (4346) bridge_wifi: sta ssid: ****** password: ******
W (4352) vendor_ie: Error Get[4354]
W (4355) vendor_ie: Error Get[4354]
I (5079) wifi:Total power save buffer number: 4
I (5084) bridge_wifi: softap ssid: ESP_Bridge_320029 password: 12345678
I (5085) Mesh-Lite: esp-mesh-lite component version: 0.7.0
Mesh-Lite commit id: 34377a9
I (5092) vendor_ie: Mesh ID: 77
W (5095) vendor_ie: Error Get[4354]
W (5099) vendor_ie: Error Get[4354]
I (5106) ESP_Mesh_Lite_Comm: msg action add success
I (5111) Mesh-Lite: Mesh-Lite connecting
I (5112) ESP_Mesh_Lite_Comm: Bind Socket 48, port 6364
I (5120) ESP_Mesh_Lite_Comm: Bind Socket 49, port 6363
I (5125) ESP_Mesh_Lite_Comm: Bind Socket 50, port 6366
I (5131) ESP_Mesh_Lite_Comm: Bind Socket 51, port 6365
I (8248) vendor_ie: Mesh-Lite Scan done
I (8323) wifi:new:<1,1>, old:<1,1>, ap:<1,1>, sta:<1,0>, prof:1
I (9040) wifi:state: init -> auth (b0)
I (9045) wifi:state: auth -> assoc (0)
I (9057) wifi:state: assoc -> run (10)
I (9304) wifi:connected with *******, aid = 7, channel 1, BW20, bssid = fc:f5:28:4b:a5:5e
I (9305) wifi:security: WPA2-PSK, phy: bgn, rssi: -50
I (9308) wifi:pm start, type: 1
I (9344) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (11182) esp_netif_handlers: sta ip: 192.168.1.41, mask: 255.255.255.0, gw: 192.168.1.1
I (11184) bridge_wifi: Connected with IP Address:192.168.1.41
I (11189) vendor_ie: RTC store: ssid:********; bssid:fc:f5:28:4b:a5:5e crc:3146113780
I (11205) Connected with IP Address:192.168.1.41
I (11278) HTTP_CLOUD_CLIENT: Initializing SNTP
`

**Comment by tswen** [comment]
Hi, could you please confirm if the following configuration items are enabled:
```
# LWIP
CONFIG_LWIP_IP_FORWARD=y
CONFIG_LWIP_IPV4_NAPT=y

CONFIG_MESH_LITE_ENABLE=y`
```

Also, it is recommended to use esp-idf/release5.0 or esp-idf/v4.4.5, as the latest tag versions have fixed some wifi bugs.

**Comment by hard-cat** [comment]
yes, these options have been disabled:
CONFIG_LWIP_IP_FORWARD=n
CONFIG_LWIP_IPV4_NAPT=n

enabling these options solved the problem, thanks :-) I will test further

**Comment by xcguang** [comment]
Could you please close this issue? If you have any other question, please raise a new one.
