### ISSUE TITLE
Examples are not compiling in Eclipse (AEGHB-403)

### ISSUE THREAD

**Issue by JL1946** [espressif/esp-mesh-lite#32]
I am having trouble compiling the esp-mesh-lite examples... the same error keeps coming up:
/Users/esp32/Projects/ESP-Mesh-Lite/esp-mesh-lite-master/examples/no_router/managed_components/espressif__esp_modem/src/esp_modem_term_uart.cpp:21:12: error: invalid conversion from 'int' to 'uart_port_t' [-fpermissive]
The problem line number is  21 -->    : port(-1)
The compiler is interpreting the -1 as an int
 
ninja: build stopped: subcommand failed.

I am using the latest esp-idf (Ver 5.1) in eclipse... 
I am using the esp-mesh-lite latest commit 671702a (updated 3 days ago as of Sept 24)

If someone can solve this issue, it will be much appreciated... Thank you

**Comment by tswen** [comment]
Do you have a working IDF environment, whether on Linux or Windows? It should be compilable without issues. I'm not aware of any specific requirements for Eclipse.

If you must compile within Eclipse, I can provide a few suggestions:

1. Perform type casting: If uart_port_t and int are involved, you can try explicit type casting by converting the integer to uart_port_t. For example:
```c++
: port(static_cast<uart_port_t>(-1))
```
2. Alternatively, you can remove : port(-1).
