### ISSUE TITLE
Communicating to child nodes (AEGHB-462)

### ISSUE THREAD

**Issue by abhimanyuarora** [espressif/esp-mesh-lite#42]
Since the only device that is directly connected to the router is the root node, if my PC is on the router network, how can I send data to any of the child nodes?

Do I use internal mesh-lite functions on the root node to send messages to the children, or can I somehow use the transport layer to do this? For example, how can I **run TCP servers on each of the child nodes**, and connect to them from my PC?

**Comment by xcguang** [comment]
You can start a TCP/UDP server on PC, then child nodes send the data to the server, and the server responds the data to the sender. About IP of PC, you can find it by root node broadcast or send MDNS.
