### ISSUE TITLE
In the example ro_router in mesh lite v0.9.0, using esp_mesh_lite_init, ports 6363, 6364, 6365, and 6366 are bound. (AEGHB-502)

### ISSUE THREAD

**Issue by sjj1507** [espressif/esp-mesh-lite#50]
idf : ESP-IDF v5.1.2-498-gc57b352725-dirty
chip: esp32c3
esp-mesh-lite component version: 0.9.0

I was wondering what ports 6363, 6364, 6365, and 6366 are used for and if there is a way to disable them.

![스크린샷 2023-12-27 123147](https://github.com/espressif/esp-mesh-lite/assets/6063762/b752771c-9bb5-4168-855c-7080dda9480d)

**Comment by tswen** [comment]
"Mesh-lite" internally also utilizes socket communication, thus occupying these four sockets and ports. May I ask for what reason it is necessary to disable these four ports?

**Comment by sjj1507** [comment]
> "Mesh-lite" internally also utilizes socket communication, thus occupying these four sockets and ports. May I ask for what reason it is necessary to disable these four ports?

I asked using 4 random ports.
I assume you are using it for internal communication of mesh lite.
