### ISSUE TITLE
esp-mesh-lite的吞吐量问题 (AEGHB-561)

### ISSUE THREAD

**Issue by kkkintama** [espressif/esp-mesh-lite#64]
各位老师好，想问一下mesh lite的最高吞吐量可以达到多少？仓库里是否有相关例程可以用于测试实时的吞吐量？

**Comment by tswen** [comment]
可以通过手机连接到不同层级的设备热点上进行测速。

**Comment by kkkintama** [comment]
> 可以通过手机连接到不同层级的设备热点上进行测速。

no_router的组网场景好像测试不了，虽然可以连上ESP_bridge，但是测不出速度。

**Comment by tswen** [comment]
或者将 iperf 功能移植到项目工程中进行测试。

**Comment by kkkintama** [comment]
> 或者将 iperf 功能移植到项目工程中进行测试。

好的，我移植看看，谢谢解答。
