### ISSUE TITLE
Mesh-lite WIFI internet event cb (AEGHB-565)

### ISSUE THREAD

**Issue by yel-best** [espressif/esp-mesh-lite#65]
I consulted some documents. I need an event that can monitor changes in the mesh lite network. 
For example, 
when mesh connected, a callback event is performed, and mesh disconnected triggers a callback event. This makes it easier for me to monitor the network status. For example, I can know what Sometimes network fluctuations are triggered within the mesh, or there are some events that I need to perform after mesh connect, such as ntp sync.

please help me,thank you

**Comment by tswen** [comment]
Mesh-Lite is entirely based on Wi-Fi's SoftAP+Station mode, so you can fully utilize Wi-Fi-related events such as WIFI_EVENT_STA_CONNECTED, WIFI_EVENT_STA_DISCONNECTED, WIFI_EVENT_AP_STACONNECTED, WIFI_EVENT_AP_STADISCONNECTED.

**Comment by yel-best** [comment]
You're right, it works for me, thank you for your help, thank you 😄
