### ISSUE TITLE
mesh后使用WIFI的API (AEGHB-643)

### ISSUE THREAD

**Issue by LYL14** [espressif/esp-mesh-lite#85]
MESH-LITE组网后，有部分设备获取不到IP.
想断开、停止、重新连接mesh-lite,但是并没有相关函数，
可以使用WIFI的断开、重连等函数，代替mesh-lite的断开吗？？？

**Comment by tswen** [comment]
可以使用 esp_mesh_lite_connect ，其作用是尝试扫描发现一个合适的父节点，然后连接到新的父节点，如果找不到合适父节点，就去连接路由器。
