### ISSUE TITLE
Can we increase Max No of layer of ESP-MESH-LITE from 15 to 20. (AEGHB-687)

### ISSUE THREAD

**Issue by mightChamp** [espressif/esp-mesh-lite#96]
As Mentioned in documentation, there is max 15 no of layers, can be achieved. 
![image](https://github.com/espressif/esp-mesh-lite/assets/45094530/792f2515-da48-4dcb-ba31-7e12b7c98404)

But my requirement is of 20.  May be there is some latency issues, But it will be ok of us.

So Can I change this value, and How to do it?

**Comment by xcguang** [comment]
Sorry, you can not change it, btw, how do you evaluate 20 layers?

**Comment by dipakbhutada** [comment]
@xcguang  Thanks for your response. Since each node is 50 meters apart, with the possibility of 20 layers, I can achieve 30-40 nodes in a single mesh. This allows me to cover a distance of 2 kilometers.

**Comment by mightChamp** [comment]
@xcguang  Thanks for your response. Since each node is 50 meters apart, with the possibility of 20 layers, I can achieve 30-40 nodes in a single mesh. This allows me to cover a distance of 2 kilometers.

**Comment by xcguang** [comment]
Now the limit is in software, for this change, and it needs some time to evaluate it.
